"""Shared generated-file contract for the Trotter package."""

from __future__ import annotations

import re
from datetime import date

CARD_NAME_PATTERN = re.compile(
    r"(?P<date>\d{4}-\d{2}-\d{2})-(?P<track>[A-Z0-9]{2,5})-full-card\.md"
)


def parse_card_name(name: str) -> tuple[str, str]:
    """Validate a card filename and return its date and track code."""
    match = CARD_NAME_PATTERN.fullmatch(name)
    if not match:
        raise ValueError(f"Noncanonical full-card filename: {name}")
    card_date = match.group("date")
    date.fromisoformat(card_date)
    return card_date, match.group("track")


def build_pick_index(card_names: list[str]) -> bytes:
    """Return the canonical picks index for full-card filenames."""
    ordered = sorted(card_names, reverse=True)
    if not ordered:
        raise ValueError("At least one full-card filename is required")
    lines = [
        "# Daily picks",
        "",
        "Full-card opinions are listed newest first. Each file preserves its original status notes, morning lines, pass conditions, reset conditions, and integrity hash.",
        "",
        "> **Safest show** means highest estimated top-three probability, not a projected third-place finisher. `ML` is the printed morning line, not live odds. Analysis is uncertain; no wager is submitted by this archive.",
        "",
        "| Date | Track | Full card | Integrity |",
        "|---|---|---|---|",
    ]
    for index, name in enumerate(ordered):
        card_date, track = parse_card_name(name)
        latest = " **(latest)**" if index == 0 else ""
        lines.append(
            f"| {card_date}{latest} | {track} | [picks](./full-card/{name}) | "
            f"[SHA-256](./full-card/{name}.sha256) |"
        )
    newest = ordered[0]
    lines.extend(
        [
            "",
            "## Verify an integrity lock",
            "",
            "Checksum paths are relative to this `picks/` directory:",
            "",
            "```bash",
            "cd picks",
            f"shasum -a 256 -c full-card/{newest}.sha256",
            "```",
            "",
            "## Publication boundary",
            "",
            "This directory publishes Trotter's original analysis and limited facts derived from the cited race forms, including horse names, figures, workout ranks, conditions, and connection records. Source DRF PDFs, screenshots, bulk extracted PP text, and official chart documents are not redistributed; third-party data remains subject to its owner's terms.",
            "",
            "Generated by `scripts/sync_from_local.py`.",
            "",
        ]
    )
    return "\n".join(lines).encode("utf-8")
